version: '3.1'

services:
    mysql:
        image: mysql:latest
        #  command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: pms
            MYSQL_DATABASE: pms
            MYSQL_USER: pms
            MYSQL_PASSWORD: dotnet8
        ports:
            - '3307:3306'
        volumes:
            # - ./data/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
            # - ./data/populate_db.sql:/docker-entrypoint-initdb.d/populate_db.sql
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
